source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

pod 'ObjectiveSugar', '~> 1.1.0'
pod 'JSQMessagesViewController'
pod 'QuickBlox'
pod 'DateTools'
pod 'Toast', '~> 2.4'

pod 'MBFaker',     '~> 0.1.2'
pod 'Specta',      '~> 0.2.1'
pod 'Expecta',     '~> 1.0.0'
pod 'OCMockito',   '~> 1.4.0'
